version: '3'
services:
  koi_node:
    command: node index
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - '8080:8080'
    environment:
      - REDIS_IP=host.docker.internal
      - REDIS_PORT=6379
      - NODE_MODE=service
      - AR_WALLET=/var/lib/koi/wallet.json
      - SERVER_PORT=8080
    container_name: koi_node
    volumes:
      - ./:/app/
      - notused:/app/node_modules
      - /pat/to/wallet.json:/var/lib/koi/wallet.json

volumes:
  notused: