version: '3'
services:
  redis:
    image: redis:alpine
    container_name: redis_db
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - ./data/:/data/
    restart: always
    networks:
      - redis_net

  koi_node:
    command: node index
    depends_on: 
      - redis
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - '8080:8080'
    environment:
      - REDIS_IP=redis
      - REDIS_PORT=6379
      - NODE_MODE=service
      - AR_WALLET=/var/lib/koi/wallet.json
      - SERVER_PORT=8080
    container_name: koi_node
    restart: always
    links:
      - redis:redis
    networks:
      - redis_net
    volumes:
      - ./:/app/
      - notused:/app/node_modules/
      - /path/to/wallet.json:/var/lib/koi/wallet.json

networks:
  redis_net:
    driver: bridge

volumes:
  notused: