module.exports = {
  RESPONSE_AUTH_INVALID: 400,
  RESPONSE_AUTH_FAIL: 401,
  RESPONSE_NOT_FOUND: 404,
  RESPONSE_USER_ERROR: 405,
  RESPONSE_INPUT_MISSING: 406,
  RESPONSE_CONFLICT: 409,
  RESPONSE_AUTH_ROLE_REQUIRED: 410,
  RESPONSE_ACTION_FAILED: 411,
  RESPONSE_SESSION_TOKEN_EXPIRED: 422,
  RESPONSE_ADMIN_PORTAL_ERROR: 407
};
